### PR TITLE
Update Changelog after #127

### PR DESCRIPTION
**Pull request by fgsch**
Forgot to include this in the original PR.

### CODE REVIEW

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by cee-dub** [comment]
Looks like we need to bump CI down to 1.22.6 to get tests passing for TinyGo, though support seems not too far off.

**Comment by dgryski** [comment]
TinyGo release supporting 1.23 coming "soon".  But fine to bump that later.

**Comment by dgryski** [comment]
https://github.com/tinygo-org/tinygo/releases/tag/v0.33.0

**Comment by dgryski** [comment]
The `main` branch now has support for TinyGo 0.33 and Go 1.23.  You can rebase this and CI should be clean.

**Pull request closed without merging**
