### PR TITLE
use latest staticcheck in validate GH action

### PR DESCRIPTION
**Pull request by joeshaw**

### CODE REVIEW

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by dgryski** [comment]
Merging because my own PR is failing because of this.

**Comment by joeshaw** [comment]
Unfortunately this is insufficient: `nilness` is still breaking.  Should we switch pulling from `master` or drop its check entirely?

**Comment by dgryski** [comment]
I don't see a problem with pulling `nilness` from `master`.  I don't want to drop the check because it catches subtle bugs and has virtually no false positives.

**Comment by joeshaw** [comment]
Ok.  Opened https://github.com/fastly/compute-sdk-go/pull/30 for that.

**Pull request merged**
