### PR TITLE
fsthttp, internal: add get_addr_dest_ip/port hostcalls

### LINKED ISSUE #121: Implement two hostcalls for obtaining address/port used to connect to origin
Two hostcalls were recently added. Support for them has already been added in the Rust SDK, but should also be added in the Go SDK.

### PR DESCRIPTION
**Pull request by dgryski**
Fixes #121

### CODE REVIEW

**Comment by dgryski** [comment]
Not sure I like how these hostcalls are exposed, but the hostcalls themselves work.

**Comment by ydnar** [comment]
Can you add a `RemoteAddr()` method to return a `net.Addr` instead of exposing host and port as fields on `Response`?

**Comment by cee-dub** [comment]
Agree with other comments that this should be a method to return a friendly standard Go type.

**Comment by joeshaw** [comment]
Consider exposing this as a `net/netip.AddrPort` instead of or in addition to a `net.Addr`

**Comment by dgryski** [comment]
API fixed. PTAL.

**Review by cee-dub — APPROVED** [review]
LGTM

**Pull request merged**
