### PR TITLE
fsthttp: add Error() and NotFound() helpers

### PR DESCRIPTION
**Pull request by dgryski**

### CODE REVIEW

**Review by Integralist — APPROVED** [review]
LGTM. 

Maybe we could also add usage of these to one of the existing examples we have?

**Comment by dgryski** [comment]
I'll submit a followup PR moving our examples and integration tests to the new API.

**Comment by dgryski** [comment]
Easy enough to do with semgrep and then a few fixups by hand.

**Review by Integralist — APPROVED** [review]

**Comment by dgryski** [comment]
```
Error: ✖ [compute-sdk-test] [error] [DownstreamResponse: Body mismatch] Expected: Unauthorized - Got: Unauthorized
```

Probably due to newline mismatch.  I'll come up with something..

**Comment by dgryski** [comment]
PTAL

**Review by Integralist — APPROVED** [review]

**Pull request merged**
